# src/export.py
import numpy as np

def write_s2p(path, freqs, S11, S21, S12=None, S22=None, fmt="RI", Z0=50):
    # 간단한 .s2p writer (RI 형식)
    if S12 is None: S12 = S21
    if S22 is None: S22 = S11
    with open(path, "w") as f:
        f.write(f"! Generated by rf_cap_designer\n# Hz S RI R {Z0}\n")
        for i, freq in enumerate(freqs):
            f.write(f"{freq:.6e}  {S11[i].real:.6e} {S11[i].imag:.6e}  "
                    f"{S21[i].real:.6e} {S21[i].imag:.6e}  "
                    f"{S12[i].real:.6e} {S12[i].imag:.6e}  "
                    f"{S22[i].real:.6e} {S22[i].imag:.6e}\n")
